apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db-api
spec:
  selector:
    matchLabels:
      app: postgres-db-api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:.
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: postgres-db-api
    spec:
      containers:
        - image: 239534/postgres_db_api
          name: postgres-db-api
          ports:
            - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: get-row-api
spec:
  selector:
    matchLabels:
      app: get-row-api
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: get-row-api
    spec:
      containers:
        - image: 239534/get_row_api:latest
          resources:
            requests:
              memory: "20Mi"
          imagePullPolicy: Always
          name: get-row-api
          livenessProbe:
            httpGet:
              path: /1
              port: 5000
            initialDelaySeconds: 15
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: postgrapi
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-db-api
---
apiVersion: v1
kind: Service
metadata:
  name: getrowapi
spec:
  type: NodePort
  selector:
    app: get-row-api
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30007
